# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - joint_trajectory_controller

  joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - X_joint
      - Y_joint
      - Z_joint
    constraints:
      goal_time: 5.0
      stopped_velocity_tolerance: 0.05
      X_joint: { trajectory: 0.10, goal: 0.05 }
      Y_joint: { trajectory: 0.10, goal: 0.05 }
      Z_joint: { trajectory: 0.10, goal: 0.05 }