# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - joint_trajectory_controller

  joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - X_joint
      - Y_joint
      - Z_joint
    # constraints:
    #   stopped_velocity_tolerance: 0.10
    #   goal_time: 10.0  # Allow more time to reach the goal
    #   X_joint: { trajectory: 0.30, goal: 0.20 }
    #   Y_joint: { trajectory: 0.30, goal: 0.20 }
    #   Z_joint: { trajectory: 0.30, goal: 0.20 }