controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - test_joint
      
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    # Increased tolerances for testing
    constraints:
      stopped_velocity_tolerance: 0.1    # Increased from 0.01
      goal_time: 0.0
      test_joint:
        trajectory: 0.5                  # Increased from 0.05
        goal: 0.3                       # Increased from 0.03

    # Allow partial movements
    allow_partial_joints_goal: true      # Added this
    
    # Optionally, can disable state checking during testing
    state_tolerance_check: false         # Added this
arctos_hardware_interface:
  ros__parameters:
    motors:
      test_joint:
        motor_id: 3
        requires_homing: false